### ISSUE TITLE
ack code-gen iam failed - Group redeclared in this block / other declaration of Group

### ISSUE THREAD

**Issue by haarchri** [crossplane/provider-aws#1025]
### What happened?

code-gen for `iam` failed with - Group redeclared in this block / other declaration of Group
https://github.com/aws-controllers-k8s/community/issues/1108

![image](https://user-images.githubusercontent.com/21083497/146688304-2027f1e4-cc9e-4777-b544-81386280437b.png)

```
20:12:21 [ .. ] go generate darwin_amd64
panic: interface conversion: types.Type is nil, not *types.Named

goroutine 1 [running]:
sigs.k8s.io/controller-tools/pkg/deepcopy.shouldBeCopied(0xc000b86720, 0xc005800ae0, 0x1003501)
        /Users/haarchri/Documents/provider-aws/.work/pkg/pkg/mod/sigs.k8s.io/controller-tools@v0.6.2/pkg/deepcopy/traverse.go:622 +0x374
sigs.k8s.io/controller-tools/pkg/deepcopy.(*ObjectGenCtx).generateForPackage.func1(0xc005800ae0)
        /Users/haarchri/Documents/provider-aws/.work/pkg/pkg/mod/sigs.k8s.io/controller-tools@v0.6.2/pkg/deepcopy/gen.go:230 +0xaf
sigs.k8s.io/controller-tools/pkg/markers.EachType.func1(0xc0063ab600, 0xc0055d5580, 0xc0056515f0)
        /Users/haarchri/Documents/provider-aws/.work/pkg/pkg/mod/sigs.k8s.io/controller-tools@v0.6.2/pkg/markers/zip.go:179 +0x76e
sigs.k8s.io/controller-tools/pkg/loader.(*typeVisitor).Visit(0xc00579e570, 0x19da2a8, 0xc0056515f0, 0x0, 0x0)
        /Users/haarchri/Documents/provider-aws/.work/pkg/pkg/mod/sigs.k8s.io/controller-tools@v0.6.2/pkg/loader/visit.go:64 +0x151
go/ast.Walk(0x19d5340, 0xc00579e570, 0x19da2a8, 0xc0056515f0)
        /Users/haarchri/.gvm/gos/go1.16/src/go/ast/walk.go:52 +0x63
go/ast.Walk(0x19d5340, 0xc00579e570, 0x19d9f10, 0xc0055d5580)
        /Users/haarchri/.gvm/gos/go1.16/src/go/ast/walk.go:331 +0xe89
go/ast.walkDeclList(0x19d5340, 0xc00579e570, 0xc005640800, 0x2a, 0x40)
        /Users/haarchri/.gvm/gos/go1.16/src/go/ast/walk.go:38 +0x9e
go/ast.Walk(0x19d5340, 0xc00579e570, 0x19d9e48, 0xc0063ab600)
        /Users/haarchri/.gvm/gos/go1.16/src/go/ast/walk.go:353 +0x2446
sigs.k8s.io/controller-tools/pkg/loader.EachType(0xc000b86720, 0xc00579e558)
        /Users/haarchri/Documents/provider-aws/.work/pkg/pkg/mod/sigs.k8s.io/controller-tools@v0.6.2/pkg/loader/visit.go:38 +0xaa
sigs.k8s.io/controller-tools/pkg/markers.EachType(0xc00088fcf8, 0xc000b86720, 0xc0057bbd40, 0x8, 0xc0077523e8)
        /Users/haarchri/Documents/provider-aws/.work/pkg/pkg/mod/sigs.k8s.io/controller-tools@v0.6.2/pkg/markers/zip.go:155 +0xa7
sigs.k8s.io/controller-tools/pkg/deepcopy.(*ObjectGenCtx).generateForPackage(0xc00093fb50, 0xc000b86720, 0x0, 0x0, 0x0)
        /Users/haarchri/Documents/provider-aws/.work/pkg/pkg/mod/sigs.k8s.io/controller-tools@v0.6.2/pkg/deepcopy/gen.go:220 +0x1e5
sigs.k8s.io/controller-tools/pkg/deepcopy.Generator.Generate(0xc00003f59b, 0x1a, 0x0, 0x0, 0xc0001100a0, 0xc00022f201, 0x2fdde58)
        /Users/haarchri/Documents/provider-aws/.work/pkg/pkg/mod/sigs.k8s.io/controller-tools@v0.6.2/pkg/deepcopy/gen.go:155 +0x1af
sigs.k8s.io/controller-tools/pkg/genall.(*Runtime).Run(0xc0007fbb80, 0xc0001fdb80)
        /Users/haarchri/Documents/provider-aws/.work/pkg/pkg/mod/sigs.k8s.io/controller-tools@v0.6.2/pkg/genall/genall.go:207 +0x1b7
main.main.func1(0xc000228280, 0xc0001fdb80, 0x4, 0x4, 0x0, 0x0)
        /Users/haarchri/Documents/provider-aws/.work/pkg/pkg/mod/sigs.k8s.io/controller-tools@v0.6.2/cmd/controller-gen/main.go:176 +0xba
github.com/spf13/cobra.(*Command).execute(0xc000228280, 0xc0000300b0, 0x4, 0x4, 0xc000228280, 0xc0000300b0)
        /Users/haarchri/Documents/provider-aws/.work/pkg/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000228280, 0xc00000ce10, 0x4, 0x0)
        /Users/haarchri/Documents/provider-aws/.work/pkg/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/haarchri/Documents/provider-aws/.work/pkg/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
        /Users/haarchri/Documents/provider-aws/.work/pkg/pkg/mod/sigs.k8s.io/controller-tools@v0.6.2/cmd/controller-gen/main.go:200 +0x346
exit status 2
apis/generate.go:26: running "go": exit status 1
20:12:28 [FAIL]
make[1]: *** [go.generate] Error 1
make: *** [generate] Error 2
```

### How can we reproduce it?

create iam generator-config.yaml
make generate

### What environment did it happen in?
Crossplane version: all

**Comment by haarchri** [comment]
https://github.com/haarchri/provider-aws/tree/error/group
added fix in code-generator aws-controllers-k8s/code-generator#251 

tested rename Group to CRDGroup in code-generator - iam generation is working
https://github.com/haarchri/provider-aws/tree/fix/group

**Comment by muvaf** [comment]
These kind of conflicts will happen more frequently the more resources we add. For a permanent fix, check out these two files to see how we ended up naming those constants and variables in Terrajet:
* https://github.com/crossplane/terrajet/blob/main/pkg/pipeline/templates/groupversion_info.go.tmpl
* https://github.com/crossplane/terrajet/blob/main/pkg/pipeline/templates/crd_types.go.tmpl#L54
