### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by nodify-at** [crossplane/provider-aws#1112]
### What happened?
crossplane proder-aws is in Crashloopback since it throws an error

### How can we reproduce it?
We don't know how to reproduce this issue. See the stack trace below.

### What environment did it happen in?
crossplane/provider-aws:v0.19.1
crossplane/crossplane:v1.2.5

* Cloud provider or hardware configuration
* Kubernetes version (use `kubectl version`)
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5",  BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

Error:
```
E0201 08:57:50.928365    1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1693 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x28a77e0, 0x51088a0)
	/home/runner/work/provider-aws/provider-aws/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x92
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/runner/work/provider-aws/provider-aws/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x28a77e0, 0x51088a0)
	/opt/hostedtoolcache/go/1.14.15/x64/src/runtime/panic.go:969 +0x166
github.com/crossplane/provider-aws/pkg/controller/dynamodb/table.(*updateClient).preUpdate(0xc0017026f0, 0x34e97e0, 0xc000776c00, 0xc0000c9340, 0xc00044c150, 0xc000f868f0, 0xc000c00850)
	/home/runner/work/provider-aws/provider-aws/pkg/controller/dynamodb/table/hooks.go:307 +0x307
github.com/crossplane/provider-aws/pkg/controller/dynamodb/table.(*external).Update(0xc0004545b0, 0x34e97e0, 0xc000776c00, 0x353f6e0, 0xc0000c9340, 0x0, 0x0, 0x0)
	/home/runner/work/provider-aws/provider-aws/pkg/controller/dynamodb/table/zz_controller.go:294 +0x99
github.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile(0xc000720580, 0x34e9820, 0xc000ce46f0, 0x0, 0x0, 0xc000834460, 0x15, 0xc000ce4600, 0x0, 0x0, ...)
	/home/runner/work/provider-aws/provider-aws/vendor/github.com/crossplane/crossplane-runtime/pkg/reconciler/managed/reconciler.go:896 +0x4805
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0009a92c0, 0x34e9760, 0xc00076a080, 0x29caf40, 0xc00155d240)
	/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:293 +0x2f1
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0009a92c0, 0x34e9760, 0xc00076a080, 0xfffffffe03000000)
	/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:248 +0x202
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1(0x34e9760, 0xc00076a080)
	/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/home/runner/work/provider-aws/provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00114ef50)
	/home/runner/work/provider-aws/provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0012dbf50, 0x348a0a0, 0xc000ce4660, 0xc00076a001, 0xc000160180)
	/home/runner/work/provider-aws/provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00114ef50, 0x3b9aca00, 0x0, 0xc0002ff301, 0xc000160180)
	/home/runner/work/provider-aws/provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x34e9760, 0xc00076a080, 0xc000c00740, 0x3b9aca00, 0x0, 0xc000776901)
	/home/runner/work/provider-aws/provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x34e9760, 0xc00076a080, 0xc000c00740, 0x3b9aca00)
	/home/runner/work/provider-aws/provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:208 +0x4f9
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1e19147] 
```

**Comment by MisterMX** [comment]
Seems to be an issue with `DynamoDB`. Can you post the YAML you are using?

Also, could you update to a later version, maybe `v0.21` or even later (be aware that there are breaking changes in `v0.22`).

**Comment by nodify-at** [comment]
Updating to a later version solved this issue, thanks.
