### ISSUE TITLE
Creating Transfer Server with required fields only crashes provider AWS

### ISSUE THREAD

**Issue by tiegs** [crossplane/provider-aws#1130]
When setting up an AWS Transfer Server using crossplane providing only the required fields provider-aws crashes.
Probably more properties than just spec.forProvider.region are actually required and expected by the provider but not properly checked. Will try to find some time to analyze which those are.

**Environment:**
k8s: v1.23.1
Crossplane version: crossplane-1.6.2
Provider AWS: crossplane/provider-aws:v0.23.0

**Preconditions:**
- Crossplane and provider AWS are set up and working correctly

**Steps to reproduce:**
Apply a manifest defining an AWS Transfer server with only minimum required fields.

Example:
```
apiVersion: transfer.aws.crossplane.io/v1alpha1
kind: Server
metadata:
  name: example
spec:
  forProvider:
    region: eu-central-1
```

**Expected behaviour:**
AWS Transfer service is created or (in case there are details missing) an error status detailing the issue is written to the ressource

**Actual behaviour:**
Provider AWS crashes:
```
minikube@crossplane-playground:~$ kubectl get pod
NAME                                         READY   STATUS             RESTARTS      AGE
crossplane-cfb4cb44f-dx9pd                   1/1     Running            0             79m
crossplane-rbac-manager-d9d6c54c7-dc8tl      1/1     Running            0             79m
provider-aws-f6a4a9bdba04-5ccd7b6974-77tct   0/1     CrashLoopBackOff   6 (54s ago)   75m
```
```
minikube@crossplane-playground:~$ kubectl logs -f deploy/provider-aws-f6a4a9bdba04
I0209 11:08:07.036412       1 request.go:668] Waited for 1.029095209s due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/ec2.aws.crossplane.io/v1beta1?timeout=32s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x19aa75b]

goroutine 2800 [running]:
github.com/crossplane/provider-aws/apis/transfer/v1alpha1.(*Server).ResolveReferences(0xc0004bdd40, 0x5e2fda0, 0xc000cd4420, 0x7fda64e37b70, 0xc000684d20, 0x5455901, 0x5521ec0)
	/home/runner/work/provider-aws/provider-aws/apis/transfer/v1alpha1/referencers.go:71 +0x9b
github.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*APISimpleReferenceResolver).ResolveReferences(0xc0005fc920, 0x5e2fda0, 0xc000cd4420, 0x5e7ac28, 0xc0004bdd40, 0x0, 0x0)
	/home/runner/work/provider-aws/provider-aws/vendor/github.com/crossplane/crossplane-runtime/pkg/reconciler/managed/api.go:147 +0x107
github.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile(0xc00029fef0, 0x5e2fdd8, 0xc000f008a0, 0x0, 0x0, 0xc0012b3df0, 0x7, 0xc000f00800, 0x0, 0x0, ...)
	/home/runner/work/provider-aws/provider-aws/vendor/github.com/crossplane/crossplane-runtime/pkg/reconciler/managed/reconciler.go:655 +0x9fd1
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00002b680, 0x5e2fd30, 0xc000976000, 0x5029500, 0xc001a9dc40)
	/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:298 +0x30d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00002b680, 0x5e2fd30, 0xc000976000, 0x5339e00)
	/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:253 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2(0xc001384090, 0xc00002b680, 0x5e2fd30, 0xc000976000)
	/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:214 +0x6b
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:210 +0x425
```

**Comment by chlunde** [comment]
FYI, I think this is the relevant line.
```go
                CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.CustomEndpointDetails.SubnetIDs),

```

I think we should try to generate the referencers using code gen and check if the appropriate if-condition will be added automatically then.

**Comment by tiegs** [comment]
Thank you for the **really** quick response and fix - great work guys!
