### ISSUE TITLE
Provider-aws panics on nil pointer dereference on security group with invalid userIdGroupPairs

### ISSUE THREAD

**Issue by blut** [crossplane/provider-aws#678]
### What happened?
After deploying an ec2.aws.crossplane.io/v1beta1 SecurityGroup the provider-aws container crashed with a nil pointer dereference error:
```
E0525 08:40:37.577973       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1584 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x26bdd20, 0x4d27a20)
        /home/runner/work/provider-aws/provider-aws/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/runtime/runtime.go:74 +0x92
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /home/runner/work/provider-aws/provider-aws/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/runtime/runtime.go:48 +0x82
panic(0x26bdd20, 0x4d27a20)
        /opt/hostedtoolcache/go/1.14.15/x64/src/runtime/panic.go:969 +0x166
github.com/crossplane/provider-aws/pkg/clients/ec2.GenerateIPPermissions.func1(0x1, 0x0, 0xc001b3c4a0)
        /home/runner/work/provider-aws/provider-aws/pkg/clients/ec2/securitygroup.go:153 +0x3d
sort.insertionSort_func(0xc001b3c5a0, 0xc0030defc0, 0x0, 0x3)
        /opt/hostedtoolcache/go/1.14.15/x64/src/sort/zfuncversion.go:12 +0xb1
sort.quickSort_func(0xc001b3c5a0, 0xc0030defc0, 0x0, 0x3, 0x4)
        /opt/hostedtoolcache/go/1.14.15/x64/src/sort/zfuncversion.go:158 +0x1f3
sort.Slice(0x24c1280, 0xc0030e2600, 0xc001b3c5a0)
        /opt/hostedtoolcache/go/1.14.15/x64/src/sort/slice.go:17 +0xf1
github.com/crossplane/provider-aws/pkg/clients/ec2.GenerateIPPermissions(0xc002ef3380, 0x3, 0x3, 0xc0030e0ae0, 0x3, 0x3)
        /home/runner/work/provider-aws/provider-aws/pkg/clients/ec2/securitygroup.go:152 +0x5f7
github.com/crossplane/provider-aws/pkg/clients/ec2.CreateSGPatch(0xc001339550, 0xc0013395e0, 0xc001339680, 0xc002ef3380, 0x3, 0x3, 0xc000b8ab00, 0x1, 0x1, 0xc002568100, ...)
        /home/runner/work/provider-aws/provider-aws/pkg/clients/ec2/securitygroup.go:277 +0x1b2
github.com/crossplane/provider-aws/pkg/clients/ec2.IsSGUpToDate(0x0, 0xc00049f780, 0x7f, 0xc000cee120, 0x25, 0xc002d27680, 0x3, 0x3, 0x0, 0x0, ...)
        /home/runner/work/provider-aws/provider-aws/pkg/clients/ec2/securitygroup.go:327 +0x82
github.com/crossplane/provider-aws/pkg/controller/ec2/securitygroup.(*external).Observe(0xc000e293c0, 0x32695c0, 0xc002dabaa0, 0x32bcdc0, 0xc00259dc00, 0x326a140, 0xc000e293c0, 0x0, 0x0)
        /home/runner/work/provider-aws/provider-aws/pkg/controller/ec2/securitygroup/controller.go:133 +0x432
github.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile(0xc0008c2e60, 0x3269600, 0xc0013513e0, 0x0, 0x0, 0xc000cee090, 0x25, 0xc001351300, 0x0, 0x0, ...)
        /home/runner/work/provider-aws/provider-aws/.work/pkg/pkg/mod/github.com/crossplane/crossplane-runtime@v0.13.0/pkg/reconciler/managed/reconciler.go:577 +0x11e1
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0008c2f00, 0x3269540, 0xc000908d00, 0x27c9c00, 0xc0013ca640)
        /home/runner/work/provider-aws/provider-aws/.work/pkg/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:293 +0x2f1
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0008c2f00, 0x3269540, 0xc000908d00, 0x0)
        /home/runner/work/provider-aws/provider-aws/.work/pkg/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:248 +0x202
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1(0x3269540, 0xc000908d00)
        /home/runner/work/provider-aws/provider-aws/.work/pkg/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:211 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
        /home/runner/work/provider-aws/provider-aws/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0009d8750)
        /home/runner/work/provider-aws/provider-aws/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001b3df50, 0x320eaa0, 0xc000edcde0, 0xc000908d01, 0xc0008690e0)
        /home/runner/work/provider-aws/provider-aws/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0009d8750, 0x3b9aca00, 0x0, 0x1, 0xc0008690e0)
        /home/runner/work/provider-aws/provider-aws/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x3269540, 0xc000908d00, 0xc001145020, 0x3b9aca00, 0x0, 0x1)
        /home/runner/work/provider-aws/provider-aws/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x3269540, 0xc000908d00, 0xc001145020, 0x3b9aca00)
        /home/runner/work/provider-aws/provider-aws/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /home/runner/work/provider-aws/provider-aws/.work/pkg/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:208 +0x4f9
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1d48f9d]

goroutine 1584 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /home/runner/work/provider-aws/provider-aws/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/runtime/runtime.go:55 +0x105
panic(0x26bdd20, 0x4d27a20)
        /opt/hostedtoolcache/go/1.14.15/x64/src/runtime/panic.go:969 +0x166
github.com/crossplane/provider-aws/pkg/clients/ec2.GenerateIPPermissions.func1(0x1, 0x0, 0xc001b3c4a0)
        /home/runner/work/provider-aws/provider-aws/pkg/clients/ec2/securitygroup.go:153 +0x3d
sort.insertionSort_func(0xc001b3c5a0, 0xc0030defc0, 0x0, 0x3)
        /opt/hostedtoolcache/go/1.14.15/x64/src/sort/zfuncversion.go:12 +0xb1
sort.quickSort_func(0xc001b3c5a0, 0xc0030defc0, 0x0, 0x3, 0x4)
        /opt/hostedtoolcache/go/1.14.15/x64/src/sort/zfuncversion.go:158 +0x1f3
sort.Slice(0x24c1280, 0xc0030e2600, 0xc001b3c5a0)
        /opt/hostedtoolcache/go/1.14.15/x64/src/sort/slice.go:17 +0xf1
github.com/crossplane/provider-aws/pkg/clients/ec2.GenerateIPPermissions(0xc002ef3380, 0x3, 0x3, 0xc0030e0ae0, 0x3, 0x3)
        /home/runner/work/provider-aws/provider-aws/pkg/clients/ec2/securitygroup.go:152 +0x5f7
github.com/crossplane/provider-aws/pkg/clients/ec2.CreateSGPatch(0xc001339550, 0xc0013395e0, 0xc001339680, 0xc002ef3380, 0x3, 0x3, 0xc000b8ab00, 0x1, 0x1, 0xc002568100, ...)
        /home/runner/work/provider-aws/provider-aws/pkg/clients/ec2/securitygroup.go:277 +0x1b2
github.com/crossplane/provider-aws/pkg/clients/ec2.IsSGUpToDate(0x0, 0xc00049f780, 0x7f, 0xc000cee120, 0x25, 0xc002d27680, 0x3, 0x3, 0x0, 0x0, ...)
        /home/runner/work/provider-aws/provider-aws/pkg/clients/ec2/securitygroup.go:327 +0x82
github.com/crossplane/provider-aws/pkg/controller/ec2/securitygroup.(*external).Observe(0xc000e293c0, 0x32695c0, 0xc002dabaa0, 0x32bcdc0, 0xc00259dc00, 0x326a140, 0xc000e293c0, 0x0, 0x0)
        /home/runner/work/provider-aws/provider-aws/pkg/controller/ec2/securitygroup/controller.go:133 +0x432
github.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile(0xc0008c2e60, 0x3269600, 0xc0013513e0, 0x0, 0x0, 0xc000cee090, 0x25, 0xc001351300, 0x0, 0x0, ...)
        /home/runner/work/provider-aws/provider-aws/.work/pkg/pkg/mod/github.com/crossplane/crossplane-runtime@v0.13.0/pkg/reconciler/managed/reconciler.go:577 +0x11e1
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0008c2f00, 0x3269540, 0xc000908d00, 0x27c9c00, 0xc0013ca640)
        /home/runner/work/provider-aws/provider-aws/.work/pkg/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:293 +0x2f1
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0008c2f00, 0x3269540, 0xc000908d00, 0x0)
        /home/runner/work/provider-aws/provider-aws/.work/pkg/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:248 +0x202
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1(0x3269540, 0xc000908d00)
        /home/runner/work/provider-aws/provider-aws/.work/pkg/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:211 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
        /home/runner/work/provider-aws/provider-aws/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0009d8750)
        /home/runner/work/provider-aws/provider-aws/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001b3df50, 0x320eaa0, 0xc000edcde0, 0xc000908d01, 0xc0008690e0)
        /home/runner/work/provider-aws/provider-aws/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0009d8750, 0x3b9aca00, 0x0, 0x1, 0xc0008690e0)
        /home/runner/work/provider-aws/provider-aws/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x3269540, 0xc000908d00, 0xc001145020, 0x3b9aca00, 0x0, 0x1)
        /home/runner/work/provider-aws/provider-aws/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x3269540, 0xc000908d00, 0xc001145020, 0x3b9aca00)
        /home/runner/work/provider-aws/provider-aws/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /home/runner/work/provider-aws/provider-aws/.work/pkg/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:208 +0x4f9
```

The SecruityGroup contained the following invalid configuration. Here ingress[1] is invalid, since mandatory information is missing.
```
spec:
  deletionPolicy: Orphan
  forProvider:
    description: EKS created security group applied to ENI that is attached to EKS
      Control Plane master nodes, as well as any managed workloads.
    groupName: eks-cluster-sg-1234567890
    ingress:
    - fromPort: 3
      ipProtocol: icmp
      ipRanges:
      - cidrIp: 0.0.0.0/0
        description: kubernetes.io/rule/nlb/mtu
      toPort: 4
    - fromPort: -1
      ipProtocol: "-1"
      userIdGroupPairs:
      - groupId: <ext. sgId>
      - groupId: <ext. sgId>
      toPort: -1
    vpcId: <vpcId>
```

My expectation would be, that provider-aws returns an event and stops processing the object, but doesn't panic.

### How can we reproduce it?
<> (s. above)

### What environment did it happen in?
Crossplane version: v0.17.0

**Comment by blut** [comment]
Looking at the code I'd venture, that there is no error handling in case any pointers are invalid:
https://github.com/crossplane/provider-aws/blob/master/pkg/clients/ec2/securitygroup.go#L141-L155

**Comment by blut** [comment]
Tested against master:HEAD (f3b901b0c0dbf3e542c35556cc7886f3160d2400) and v0.18.1: Nil pointer dereference has been fixed
