### ISSUE TITLE
panic when importing existing AWS route table or creating a new one

### ISSUE THREAD

**Issue by doubliez** [crossplane/provider-aws#795]
### What happened?
Trying to import an existing route table into Crossplane crashes provider-aws with a panic.

Here is the manifest I'm applying (I just obfuscated the resource IDs):
```yaml
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTable
metadata:
  name: rtb-int-private
  annotations:
    crossplane.io/external-name: rtb-xxxxxxxx
spec:
  forProvider:
    associations:
      - subnetIdRef:
          name: int-private-a
      - subnetIdRef:
          name: int-private-b
      - subnetIdRef:
          name: int-private-c
    region: us-west-2
    routes:
      - destinationCidrBlock: 0.0.0.0/0
        transitGatewayId: tgw-xxxxxxxx
      - destinationIpv6CidrBlock: ::/0
        egressOnlyInternetGatewayId: eigw-xxxxxxxx
      - destinationCidrBlock: 192.168.248.0/21
        vpcPeeringConnectionId: pcx-xxxxxxxx
    vpcIdRef:
      name: sst-integration
  providerConfigRef:
    name: aws-integration
  deletionPolicy: Orphan
```

Note that the actual route table in AWS is configured the same as in the manifest (with the 3 subnet associations, and the 3 routes).

Here is the error in provider-aws:
```
E0809 23:29:29.689428       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1575 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x28a5580, 0x51038a0)
	/home/runner/work/provider-aws/provider-aws/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x92
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/runner/work/provider-aws/provider-aws/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x28a5580, 0x51038a0)
	/opt/hostedtoolcache/go/1.14.15/x64/src/runtime/panic.go:969 +0x166
github.com/crossplane/provider-aws/pkg/clients/ec2.SortRoutes.func1(0x1, 0x0, 0xc001bf47b0)
	/home/runner/work/provider-aws/provider-aws/pkg/clients/ec2/routetable.go:217 +0x6f
sort.insertionSort_func(0xc001bf4830, 0xc001596db0, 0x0, 0x6)
	/opt/hostedtoolcache/go/1.14.15/x64/src/sort/zfuncversion.go:12 +0xb1
sort.quickSort_func(0xc001bf4830, 0xc001596db0, 0x0, 0x6, 0x6)
	/opt/hostedtoolcache/go/1.14.15/x64/src/sort/zfuncversion.go:158 +0x1f3
sort.Slice(0x26711a0, 0xc001170020, 0xc001bf4830)
	/opt/hostedtoolcache/go/1.14.15/x64/src/sort/slice.go:17 +0xf1
github.com/crossplane/provider-aws/pkg/clients/ec2.SortRoutes(0xc001a538c0, 0x6, 0x6, 0xc0000e3680, 0x5, 0x5)
	/home/runner/work/provider-aws/provider-aws/pkg/clients/ec2/routetable.go:216 +0xa4
github.com/crossplane/provider-aws/pkg/clients/ec2.CreateRTPatch(0xc001f45830, 0x3, 0x3, 0xc0010220c0, 0x0, 0x0, 0x0, 0xc0010220f0, 0xc0000e3680, 0x5, ...)
	/home/runner/work/provider-aws/provider-aws/pkg/clients/ec2/routetable.go:178 +0x1db
github.com/crossplane/provider-aws/pkg/clients/ec2.IsRtUpToDate(0xc0018deb80, 0x9, 0xc00183b310, 0x3, 0x3, 0xc00089db00, 0x5, 0x5, 0xc0009b7a40, 0x2, ...)
	/home/runner/work/provider-aws/provider-aws/pkg/clients/ec2/routetable.go:202 +0x83
github.com/crossplane/provider-aws/pkg/controller/ec2/routetable.(*external).Observe(0xc0007c6320, 0x34e69c0, 0xc001a73ec0, 0x353d040, 0xc000536480, 0x34e7540, 0xc0007c6320, 0x0, 0x0)
	/home/runner/work/provider-aws/provider-aws/pkg/controller/ec2/routetable/controller.go:148 +0x44b
github.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile(0xc000474f00, 0x34e6a00, 0xc0009e1dd0, 0x0, 0x0, 0xc0016193c0, 0x1a, 0xc0009e1d00, 0x0, 0x0, ...)
	/home/runner/work/provider-aws/provider-aws/vendor/github.com/crossplane/crossplane-runtime/pkg/reconciler/managed/reconciler.go:614 +0x1d58
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000474fa0, 0x34e6940, 0xc00076ce40, 0x29c8b40, 0xc000339f80)
	/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:293 +0x2f1
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000474fa0, 0x34e6940, 0xc00076ce40, 0x0)
	/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:248 +0x202
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1(0x34e6940, 0xc00076ce40)
	/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/home/runner/work/provider-aws/provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc001572f50)
	/home/runner/work/provider-aws/provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001bf5f50, 0x34872c0, 0xc0010b4f30, 0xc00076ce01, 0xc0000d95c0)
	/home/runner/work/provider-aws/provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001572f50, 0x3b9aca00, 0x0, 0x1, 0xc0000d95c0)
	/home/runner/work/provider-aws/provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x34e6940, 0xc00076ce40, 0xc0007cad10, 0x3b9aca00, 0x0, 0x2f1a901)
	/home/runner/work/provider-aws/provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x34e6940, 0xc00076ce40, 0xc0007cad10, 0x3b9aca00)
	/home/runner/work/provider-aws/provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:208 +0x4f9
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1e259ff]

goroutine 1575 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/runner/work/provider-aws/provider-aws/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x28a5580, 0x51038a0)
	/opt/hostedtoolcache/go/1.14.15/x64/src/runtime/panic.go:969 +0x166
github.com/crossplane/provider-aws/pkg/clients/ec2.SortRoutes.func1(0x1, 0x0, 0xc001bf47b0)
	/home/runner/work/provider-aws/provider-aws/pkg/clients/ec2/routetable.go:217 +0x6f
sort.insertionSort_func(0xc001bf4830, 0xc001596db0, 0x0, 0x6)
	/opt/hostedtoolcache/go/1.14.15/x64/src/sort/zfuncversion.go:12 +0xb1
sort.quickSort_func(0xc001bf4830, 0xc001596db0, 0x0, 0x6, 0x6)
	/opt/hostedtoolcache/go/1.14.15/x64/src/sort/zfuncversion.go:158 +0x1f3
sort.Slice(0x26711a0, 0xc001170020, 0xc001bf4830)
	/opt/hostedtoolcache/go/1.14.15/x64/src/sort/slice.go:17 +0xf1
github.com/crossplane/provider-aws/pkg/clients/ec2.SortRoutes(0xc001a538c0, 0x6, 0x6, 0xc0000e3680, 0x5, 0x5)
	/home/runner/work/provider-aws/provider-aws/pkg/clients/ec2/routetable.go:216 +0xa4
github.com/crossplane/provider-aws/pkg/clients/ec2.CreateRTPatch(0xc001f45830, 0x3, 0x3, 0xc0010220c0, 0x0, 0x0, 0x0, 0xc0010220f0, 0xc0000e3680, 0x5, ...)
	/home/runner/work/provider-aws/provider-aws/pkg/clients/ec2/routetable.go:178 +0x1db
github.com/crossplane/provider-aws/pkg/clients/ec2.IsRtUpToDate(0xc0018deb80, 0x9, 0xc00183b310, 0x3, 0x3, 0xc00089db00, 0x5, 0x5, 0xc0009b7a40, 0x2, ...)
	/home/runner/work/provider-aws/provider-aws/pkg/clients/ec2/routetable.go:202 +0x83
github.com/crossplane/provider-aws/pkg/controller/ec2/routetable.(*external).Observe(0xc0007c6320, 0x34e69c0, 0xc001a73ec0, 0x353d040, 0xc000536480, 0x34e7540, 0xc0007c6320, 0x0, 0x0)
	/home/runner/work/provider-aws/provider-aws/pkg/controller/ec2/routetable/controller.go:148 +0x44b
github.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile(0xc000474f00, 0x34e6a00, 0xc0009e1dd0, 0x0, 0x0, 0xc0016193c0, 0x1a, 0xc0009e1d00, 0x0, 0x0, ...)
	/home/runner/work/provider-aws/provider-aws/vendor/github.com/crossplane/crossplane-runtime/pkg/reconciler/managed/reconciler.go:614 +0x1d58
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000474fa0, 0x34e6940, 0xc00076ce40, 0x29c8b40, 0xc000339f80)
	/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:293 +0x2f1
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000474fa0, 0x34e6940, 0xc00076ce40, 0x0)
	/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:248 +0x202
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1(0x34e6940, 0xc00076ce40)
	/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/home/runner/work/provider-aws/provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc001572f50)
	/home/runner/work/provider-aws/provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001bf5f50, 0x34872c0, 0xc0010b4f30, 0xc00076ce01, 0xc0000d95c0)
	/home/runner/work/provider-aws/provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001572f50, 0x3b9aca00, 0x0, 0x1, 0xc0000d95c0)
	/home/runner/work/provider-aws/provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x34e6940, 0xc00076ce40, 0xc0007cad10, 0x3b9aca00, 0x0, 0x2f1a901)
	/home/runner/work/provider-aws/provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x34e6940, 0xc00076ce40, 0xc0007cad10, 0x3b9aca00)
	/home/runner/work/provider-aws/provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:208 +0x4f9
```

### How can we reproduce it?
See above.

However I could reproduce the panic even when creating a new route table (not importing pre-existing) and not specifying any subnet association or route:
```yaml
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTable
metadata:
  name: test-new-rtb
spec:
  forProvider:
    associations: []
    region: us-west-2
    routes: []
    vpcIdRef:
      name: sst-integration
  providerConfigRef:
    name: aws-integration
  deletionPolicy: Orphan
```

With this manifest, a new route table gets created in AWS but I still observe the panic. And when trying to add some routes to this manifest, they do not get created in AWS.

### What environment did it happen in?
Crossplane version: 1.3.0
provider-aws version: 0.19.0
EKS: 1.21

**Comment by jessesuen** [comment]
Hit this issue as well on v0.26.1, when attempting to provision a VPC with ipv4/ipv6:

```
1.6512845269172087e+09  DEBUG   provider-aws    Reconciling     {"controller": "managed/address.ec2.aws.crossplane.io", "request": "/eks.akuity-test-001-jesse.natip-a"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x263a42c]

goroutine 4028 [running]:
github.com/crossplane/provider-aws/pkg/clients/ec2.SortRoutes.func1(0x1, 0x0)
        /home/runner/work/provider-aws/provider-aws/pkg/clients/ec2/routetable.go:208 +0x6c
sort.insertionSort_func({0x40029f4778, 0x4002ef8de0}, 0x0, 0x2)
        /opt/hostedtoolcache/go/1.17.8/x64/src/sort/zfuncversion.go:12 +0xb4
sort.quickSort_func({0x40029f4778, 0x4002ef8de0}, 0x0, 0x2, 0x4)
        /opt/hostedtoolcache/go/1.17.8/x64/src/sort/zfuncversion.go:158 +0x1c4
sort.Slice({0x40a7360, 0x4002ee4b40}, 0x40029f4778)
        /opt/hostedtoolcache/go/1.17.8/x64/src/sort/slice.go:20 +0xdc
github.com/crossplane/provider-aws/pkg/clients/ec2.SortRoutes({0x4002171ce0, 0x2, 0x2}, {0x400225c000, 0x2, 0x2})
        /home/runner/work/provider-aws/provider-aws/pkg/clients/ec2/routetable.go:207 +0x84
github.com/crossplane/provider-aws/pkg/clients/ec2.CreateRTPatch({{0x82532e0, 0x0, 0x0}, 0x4002ecba20, {0x82532e0, 0x0, 0x0}, 0x4002ecba00, {0x400225c000, 0x2, ...}, ...}, ...)
        /home/runner/work/provider-aws/provider-aws/pkg/clients/ec2/routetable.go:169 +0xe8
github.com/crossplane/provider-aws/pkg/clients/ec2.IsRtUpToDate({{0x4001f23504, 0x9}, {0x4001adf980, 0x3, 0x4}, {0x400054ae00, 0x1, 0x4}, {0x40026f0c80, 0x1, ...}, ...}, ...)
        /home/runner/work/provider-aws/provider-aws/pkg/clients/ec2/routetable.go:193 +0x60
github.com/crossplane/provider-aws/pkg/controller/ec2/routetable.(*external).Observe(0x40020ba110, {0x58472d0, 0x4001c8d7a0}, {0x5908920, 0x40028a4900})
        /home/runner/work/provider-aws/provider-aws/pkg/controller/ec2/routetable/controller.go:155 +0x604
github.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile(0x40007bd550, {0x5847308, 0x4002142480}, {{{0x0, 0x0}, {0x4000176060, 0x20}}})
        /home/runner/work/provider-aws/provider-aws/vendor/github.com/crossplane/crossplane-runtime/pkg/reconciler/managed/reconciler.go:767 +0x1fd0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x40007bd600, {0x5847308, 0x40021423c0}, {{{0x0, 0x0}, {0x4000176060, 0x20}}})
        /home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:114 +0x22c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0x40007bd600, {0x5847260, 0x40005af040}, {0x47d6880, 0x40026e22c0})
        /home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:311 +0x2ac
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0x40007bd600, {0x5847260, 0x40005af040})
        /home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266 +0x1d4
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2(0x4000a42570, 0x40007bd600, {0x5847260, 0x40005af040})
        /home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227 +0x60
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:223 +0x324
```
